config/routes.rb
Gardian::Application.routes.draw do

  namespace :api do
    resources :clients
  end


  namespace :admin do
    resources :clients
  end


  devise_for :admins

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  
  # Sample resource route within a namespace:
  namespace :admin do
    root :to => 'base#index'
    # Directs /admin/products/* to Admin::ProductsController
    # (app/controllers/admin/products_controller.rb)

  end
  namespace :user do
    root :to => 'entries#index'
    # Directs /admin/products/* to Admin::ProductsController
    # (app/controllers/admin/products_controller.rb)
    resources :entries
    
  end
 
  namespace :api do
    resource :user do
      member do
        post :sign_in
        get :sign_out
      end
    end

    match '/check_in', to: 'entries#check_in'
    match '/check_out', to: 'entries#check_out'
    match '/check_entry', to: 'entries#check'
    match '/list_on', to: 'entries#list_on'
    match '/show_entry', to: 'entries#show'
    match '/list_off', to: 'entries#list_off'
    match '/filter_by_name', to: 'entries#filter_by_name'
    match '/change_pass', to: 'users#change_pass'
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'
  
  match '/new_entry', to: 'home#new_entry'
  match '/save_entry', to: 'home#save_entry'
 
  match '/media/*dragonfly', :to => Dragonfly[:images]

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  
end

app/models/admin/client.rb
class Admin::Client
  include Mongoid::Document
  field :name, :type => String
  field :adresse, :type => String
end

app/models/api/client.rb
class Api::Client
  include Mongoid::Document
  field :name, :type => String
  field :adresse, :type => String
end

app/models/client.rb
class Client
  include Mongoid::Document
  field :name, :type => String
  field :adresse, :type => String
end

app/controllers/admin/clients_controller.rb
class Admin::ClientsController < ApplicationController
  # GET /admin/clients
  # GET /admin/clients.json
  def index
    @clients = Client.all
  end

  def destroy

    @client = Client.find(params[:id]) 
    @client.destroy

    respond_to do |format|
      format.html { redirect_to admin_clients_url }
      format.json { head :no_content }
    end

  end

  def new
  end

 
end

app/controllers/api/clients_controller.rb
class Api::ClientsController < ApplicationController
  # GET /api/clients
  # GET /api/clients.json
  def index
    @api_clients = Api::Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @api_clients }
    end
  end

  # GET /api/clients/1
  # GET /api/clients/1.json
  def show
    @api_client = Api::Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @api_client }
    end
  end

  # GET /api/clients/new
  # GET /api/clients/new.json
  def new
    @api_client = Api::Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @api_client }
    end
  end

  # GET /api/clients/1/edit
  def edit
    @api_client = Api::Client.find(params[:id])
  end

  # POST /api/clients
  # POST /api/clients.json
  def create
    @api_client = Api::Client.new(params[:api_client])

    respond_to do |format|
      if @api_client.save
        format.html { redirect_to @api_client, notice: 'Client was successfully created.' }
        format.json { render json: @api_client, status: :created, location: @api_client }
      else
        format.html { render action: "new" }
        format.json { render json: @api_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /api/clients/1
  # PUT /api/clients/1.json
  def update
    @api_client = Api::Client.find(params[:id])

    respond_to do |format|
      if @api_client.update_attributes(params[:api_client])
        format.html { redirect_to @api_client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @api_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api/clients/1
  # DELETE /api/clients/1.json
  def destroy
    @api_client = Api::Client.find(params[:id])
    @api_client.destroy

    respond_to do |format|
      format.html { redirect_to api_clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/admin/clients_helper.rb
module Admin::ClientsHelper
end

app/helpers/api/clients_helper.rb
module Api::ClientsHelper
end

app/views/admin/clients/_form.html.erb
<%= simple_form_for(@admin_client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :adresse %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/clients/edit.html.erb
<h1>Editing admin_client</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_client %> |
<%= link_to 'Back', admin_clients_path %>

app/views/admin/clients/index.html.erb
<h1>Listing admin_clients</h1>

<table class="table table-bordered">
  <tr>
    <th>Name</th>
    <th>Adresse</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_clients.each do |admin_client| %>
  <tr>
    <td><%= admin_client.name %></td>
    <td><%= admin_client.adresse %></td>
    <td><%= link_to 'Show', admin_client %></td>
    <td><%= link_to 'Edit', edit_admin_client_path(admin_client) %></td>
    <td><%= link_to 'Destroy', admin_client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_admin_client_path %>

app/views/admin/clients/new.html.erb
<h1>New admin_client</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_clients_path %>

app/views/admin/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @admin_client.name %>
</p>

<p>
  <b>Adresse:</b>
  <%= @admin_client.adresse %>
</p>


<%= link_to 'Edit', edit_admin_client_path(@admin_client) %> |
<%= link_to 'Back', admin_clients_path %>